######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 1 20:15:21 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
SOURCES += final.cpp widget.cpp
