######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 8 20:21:56 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += multimedia
QT += phonon

# Input
HEADERS += widget.h
SOURCES += final.cpp widget.cpp
